### ISSUE TITLE
Writing the Categories component

### ISSUE THREAD

**Issue by mkaramuk** [quikkom/quikkom-frontend#4]
![Categories](https://github.com/quikkom/quikkom-frontend/assets/39464118/24222cf7-7e73-4fcf-8c0d-4d8808ec019e)

There will be a list that looks like the one shown in the image, with links that will redirect to the category page when clicked (currently pending). Popular categories will be listed, while less popular categories will be accessible via a hamburger menu at the bottom.

- [ ] Preparation of the list
- [ ] Hamburger menu implementation

**Comment by TalhaAksoy** [comment]
This component is merged with the navbar due to changes in the ui design of the navbar. #7 #2
